CREATE TABLE "mytable" (
  "# -*- coding: utf-8 -*-" text
);

INSERT INTO "mytable" ("# -*- coding: utf-8 -*-")
VALUES
('"
Created on Tue Oct  1 19:27:48 2024

@author: adwit
"'),
('LOAD DATA INFILE ''C:/Users/adwit/OneDrive/Documents/SQL/archive'''),
('INTO TABLE your_table'),
('FIELDS TERMINATED BY '''),
('ENCLOSED BY ''"'''),
('LINES TERMINATED BY ''\n'''),
('IGNORE 1 ROWS;'),
('SELECT'),
('Extreme_Weather_Events > 0 AS Has_Extreme_Weather'),
('AVG(Crop_Yield_MT_per_HA) AS Avg_Crop_Yield'),
('FROM'),
('agriculture_impact'),
('GROUP BY'),
('Has_Extreme_Weather;'),
('SELECT'),
('Crop_Type'),
('Region'),
('AVG(CO2_Emissions_MT) AS Avg_CO2_Emissions'),
('AVG(Crop_Yield_MT_per_HA) AS Avg_Crop_Yield'),
('FROM'),
('agriculture_impact'),
('GROUP BY'),
('Crop_Type'),
('Region'),
('ORDER BY'),
('Avg_CO2_Emissions DESC;'),
('SELECT'),
('Country'),
('Region'),
('AVG(Irrigation_Access_%) AS Avg_Irrigation_Access'),
('AVG(Crop_Yield_MT_per_HA) AS Avg_Crop_Yield'),
('FROM'),
('agriculture_impact'),
('GROUP BY'),
('Country'),
('Region'),
('ORDER BY'),
('Avg_Irrigation_Access DESC;'),
('SELECT'),
('Crop_Type'),
('CASE'),
('WHEN Average_Temperature_C < 15 THEN ''Low Temperature'''),
('WHEN Average_Temperature_C BETWEEN 15 AND 25 THEN ''Moderate Temperature'''),
('ELSE ''High Temperature'''),
('END AS Temperature_Range'),
('AVG(Crop_Yield_MT_per_HA) AS Avg_Crop_Yield'),
('FROM'),
('agriculture_impact'),
('GROUP BY'),
('Crop_Type'),
('Temperature_Range;'),
('SELECT'),
('Fertilizer_Use_KG_per_HA'),
('Pesticide_Use_KG_per_HA'),
('AVG(Soil_Health_Index) AS Avg_Soil_Health'),
('AVG(Crop_Yield_MT_per_HA) AS Avg_Crop_Yield'),
('FROM'),
('agriculture_impact'),
('GROUP BY'),
('Fertilizer_Use_KG_per_HA'),
('Pesticide_Use_KG_per_HA'),
('ORDER BY'),
('Fertilizer_Use_KG_per_HA'),
('Pesticide_Use_KG_per_HA;');
